### ISSUE TITLE
java.lang.NoSuchFieldError: isSelectablePredicate in JOSM 10 663

### ISSUE THREAD

**Issue by mkyral** [Gubaer/josm-contourmerge-plugin#13]
I think, you know it, but if you did not notice, switching to contourmerge mode causes following exception in latest josm :-(

```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-07-28 01:24:39 +0200 (Thu, 28 Jul 2016)
Build-Date:2016-07-28 01:34:11
Revision:10663
Relative:URL: ^/trunk

Identification: JOSM/1.5 (10663 cs) Linux Gentoo/Linux
Memory Usage: 966 MB / 3547 MB (707 MB allocated, but free)
Java version: 1.8.0_91-b14, Oracle Corporation, OpenJDK 64-Bit Server VM
Java package: icedtea-bin:3.0.1
7.2.6.6-r1

VM arguments: [-Dawt.useSystemAAFontSettings=on, -Dswing.aatext=true]
Dataset consistency test: No problems found

Plugins:
- Create_grid_of_ways (32440)
- DirectUpload (32329)
- OpeningHoursEditor (32583)
- PicLayer (32495)
- Tracer-testing (1457538387)
- apache-commons (32584)
- apache-http (32584)
- buildings_tools (32728)
- contourmerge (1012)
- dataimport (32484)
- editgpx (32485)
- ejml (32639)
- geotools (32584)
- imagery_offset_db (32528)
- jts (32539)
- log4j (32309)
- opendata (32584)
- pointInfo (32584)
- pt_assistant (32734)
- reltoolbox (32639)
- reverter (32584)
- tofix (1468342359)
- turnrestrictions (32629)
- utilsplugin2 (32725)
- wikipedia (32671)

Tagging presets:
- <josm.pref>/plugins/presets/Presets_Trees-preset.xml
- ${HOME}/dokumenty/josm/presets/railways.zip
- ${HOME}/projekty/josm/presets/Czech_hiking_symbols/Czech_hiking_symbols.xml
- http://osmtools.de/josm/steps.xml
- http://somewhere.dk/email/josm/source.xml
- http://www.kyralovi.cz/tmp/josm/presets/address_sk_cz.xml
- https://josm.openstreetmap.de/josmfile?page=Presets/Crafts&preset&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/Czech_hiking&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/Heritage&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/Historical_Objects&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/NewParkingFeatures&preset&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/NewTags&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/OneClick&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/PublicTransportOneClick&preset&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/Quick-highways&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/Quick-stops&zip=1
- https://josm.openstreetmap.de/josmfile?page=Presets/Towers&zip=1

Map paint styles:
- ${HOME}/projekty/josm/mapcss/debug.mapcss
- https://github.com/gmgeo/osmic-josm-style/archive/master.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/AddressValidator&style&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/ConscriptionStreetnumber&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Landcover&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&style&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&style&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/NoFeature&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/NumberedWalkingNodeNetworks&style&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/OsmcSKCZPL&style&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/PublicTransport&zip=1

Validator rules:
- https://josm.openstreetmap.de/josmfile?page=Rules/CzechRepublicAddressSystem&zip=1

Last errors/warnings:
- W:  Wayside shrine: Could not get presets icon presets/chapel.png
- E: Nepodařilo se nalézt obrázek 'presets/chapel.png'
- W:  Wayside cross: Could not get presets icon presets/chapel.png
- E: Nepodařilo se nalézt obrázek 'presets/chapel.png'
- W:  Wayside cross: Could not get presets icon presets/chapel.png
- W: Plugin seems to be adding listener during mapFrameInitialized(): ContourMergeModelManager#wireToJOSM. Layer listeners should be set on plugin load.
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.tofix.TofixDialog$3@61f9a925
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.tofix.TofixDialog$4@3b68d4d0
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.tofix.TofixDialog$5@cbe6fda
- E: java.lang.NoSuchFieldError: isSelectablePredicate


=== REPORTED CRASH DATA ===
BugReportExceptionHandler$BugReporterThread#askForBugReport:
No data collected.

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (16) of main
java.lang.NoSuchFieldError: isSelectablePredicate
	at org.openstreetmap.josm.plugins.contourmerge.ContourMergeMode.mouseMoved(ContourMergeMode.java:178)
	at java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:330)
	at java.awt.Component.processMouseMotionEvent(Component.java:6580)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3333)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4538)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

**Comment by Gubaer** [comment]
I've built and published two new versions of the plugin:
* a version compatible with JOSM 10526 (currently JOSM tested), built with Java 8, but still referring to [OsmPrimitive::isSelectablePrimitive](https://github.com/openstreetmap/josm/blob/a0617497068dde5daec69bdf7aca3f06e98fab61/src/org/openstreetmap/josm/data/osm/OsmPrimitive.java#L186)  which is an instance of an anonymous inner class 
* a version compatible with JOSM 10659, built with Java 8, but now referring to the refactored [OsmPrimitive::isSelectablePrimitive](https://github.com/openstreetmap/josm/blob/e60b41148cd7f0c59c28f4593299efd534aeb109/src/org/openstreetmap/josm/data/osm/OsmPrimitive.java#L209)  which is now a Java 8 closure 

Please reinstall the plugin with your JOSM version. JOSM should automatically pick up the version which is compatible with its version.

**Comment by mkyral** [comment]
Thanks. I've tested the java8 version and works correctly.

Thanks a lot.
